### ISSUE TITLE
Vectorized tweening

### ISSUE THREAD

**Issue by paulmelnikow** [asweigart/pytweening#4]
Hi, and thanks for this useful library!

I have an application where I need to tween a numpy array of heights. It would be pretty sick if pytweening functions were vectorized, meaning they'd work on single inputs or arrays of inputs. This is fairly simple to accomplish. It might not make sense to add a dependency on numpy, which could be accomplished by doing a `try`/`catch` import of numpy, or by putting the numpy versions in a module alongside.

A fork is another option, though I thought it would be more ideal to include the functions here if possible. I'd be happy to help implement this.

Would you have any interest in including this functionality?

**Comment by asweigart** [comment]
I'm catching up on old issues. The functions of in this module are so simple, I'd wouldn't even recommend a fork but just copy/paste the functions as needed.
