### ISSUE TITLE
Move to pyproject.toml?

### ISSUE THREAD

**Issue by stefmolin** [asweigart/pytweening#7]
Any opposition to moving from `setup.py` to `pyproject.toml`? I'm happy to put in a PR.

**Comment by asweigart** [comment]
So it seems like a bug in `python -m build` causes the sdist to fail to install on Python 2.7. Unless there's a reason to move to pyproject.toml, I'm going to revert the changes back to setup.py.

Without a setup.py file, the sdist produced by `python -m build` causes pip to install an UNKNOWN-0.0.0 package on Python 2.7. I don't have time to debug this issue and with Python 2 past EOL, I don't see this bug being fixed. Given that the old setup.py still works, I don't see a reason to move forward to pyproject.toml in the case of pytweening.

**Comment by stefmolin** [comment]
You might be able to fix this by specifying a >= version for setup tools (that solved a problem I had with the UNKNOWN thing).

Note that for newer versions of Python, pip complains that pytweening doesn't have the pyproject.toml file. Maybe you can keep both?
